const fonts = [
  'Select Font',
  'Al Nile',
  'Al Tarikh',
  'AlBayan',
  'American Typewriter',
  'Andale Mono',
  'Apple Chancery',
  'AppleGothic',
  'AppleMyungjo',
  'Arial Black',
  'Arial Bold Italic',
  'Arial Bold',
  'Arial Italic',
  'Arial Narrow Bold Italic',
  'Arial Narrow Bold',
  'Arial Narrow Italic',
  'Arial Narrow',
  'Arial Rounded Bold',
  'Arial Unicode',
  'Arial',
  'Ayuthaya',
  'Baghdad',
  'Bangla MN',
  'Bangla Sangam MN',
  'Baskerville',
  'Beirut',
  'BigCaslon',
  'Bodoni 72 OS',
  'Bodoni 72 Smallcaps Book',
  'Bodoni 72',
  'Bodoni Ornaments',
  'Bradley Hand Bold',
  'Brush Script',
  'Chalkboard',
  'ChalkboardSE',
  'Chalkduster',
  'Charter',
  'Cochin',
  'Comic Sans MS Bold',
  'Comic Sans MS',
  'Copperplate',
  'Corsiva',
  'Courier New Bold Italic',
  'Courier New Bold',
  'Courier New Italic',
  'Courier New',
  'DIN Alternate Bold',
  'DIN Condensed Bold',
  'Damascus',
  'DecoTypeNaskh',
  'Devanagari Sangam MN',
  'DevanagariMT',
  'Didot',
  'Diwan Kufi',
  'Diwan Thuluth',
  'EuphemiaCAS',
  'Farah',
  'Farisi',
  'Futura',
  'Georgia Bold Italic',
  'Georgia Bold',
  'Georgia Italic',
  'Georgia',
  'GillSans',
  'Gujarati Sangam MN',
  'GujaratiMT',
  'Gurmukhi MN',
  'Gurmukhi Sangam MN',
  'Gurmukhi',
  'Herculanum',
  'Hoefler Text Ornaments',
  'Hoefler Text',
  'ITFDevanagari',
  'Impact',
  'InaiMathi-MN',
  'Kailasa',
  'Kannada MN',
  'Kannada Sangam MN',
  'Kefa',
  'Khmer MN',
  'Khmer Sangam MN',
  'Kokonor',
  'Krungthep',
  'KufiStandardGK',
  'Lao MN',
  'Lao Sangam MN',
  'Luminari',
  'Malayalam MN',
  'Malayalam Sangam MN',
  'Microsoft Sans Serif',
  'Mishafi Gold',
  'Mishafi',
  'Mshtakan',
  'Muna',
  'Myanmar MN',
  'Myanmar Sangam MN',
  'NISC18030',
  'Nadeem',
  'NewPeninimMT',
  'Oriya MN',
  'Oriya Sangam MN',
  'PTMono',
  'PTSans',
  'PTSerif',
  'PTSerifCaption',
  'Papyrus',
  'Phosphate',
  'PlantagenetCherokee',
  'Raanana',
  'Rockwell',
  'STIXGeneral',
  'STIXGeneralBol',
  'STIXGeneralBolIta',
  'STIXGeneralItalic',
  'STIXIntDBol',
  'STIXIntDReg',
  'STIXIntSmBol',
  'STIXIntSmReg',
  'STIXIntUpBol',
  'STIXIntUpDBol',
  'STIXIntUpDReg',
  'STIXIntUpReg',
  'STIXIntUpSmBol',
  'STIXIntUpSmReg',
  'STIXNonUni',
  'STIXNonUniBol',
  'STIXNonUniBolIta',
  'STIXNonUniIta',
  'STIXSizFiveSymReg',
  'STIXSizFourSymBol',
  'STIXSizFourSymReg',
  'STIXSizOneSymBol',
  'STIXSizOneSymReg',
  'STIXSizThreeSymBol',
  'STIXSizThreeSymReg',
  'STIXSizTwoSymBol',
  'STIXSizTwoSymReg',
  'STIXVar',
  'STIXVarBol',
  'Sana',
  'Sathu',
  'Savoye LET',
  'Shree714',
  'SignPainter',
  'Silom',
  'Sinhala MN',
  'Sinhala Sangam MN',
  'Skia',
  'SnellRoundhand',
  'Songti',
  'SukhumvitSet',
  'Tahoma Bold',
  'Tahoma',
  'Tamil MN',
  'Tamil Sangam MN',
  'Telugu MN',
  'Telugu Sangam MN',
  'Times New Roman Bold Italic',
  'Times New Roman Bold',
  'Times New Roman Italic',
  'Times New Roman',
  'Trattatello',
  'Trebuchet MS Bold Italic',
  'Trebuchet MS Bold',
  'Trebuchet MS Italic',
  'Trebuchet MS',
  'Verdana Bold Italic',
  'Verdana Bold',
  'Verdana Italic',
  'Verdana',
  'Waseem',
  'Webdings',
  'Wingdings 2',
  'Wingdings 3',
  'Wingdings',
  'Zapfino'
]

export default fonts
